hopefully fix CORS configuration

diff --git a/frontend/consumer-ui/chart/templates/deployment.yaml b/frontend/consumer-ui/chart/templates/deployment.yaml
--- a/frontend/consumer-ui/chart/templates/deployment.yaml
+++ b/frontend/consumer-ui/chart/templates/deployment.yaml
@@ -23,6 +23,29 @@ spec:
       serviceAccountName: {{ template "chart.serviceAccountName" . }}
       securityContext:
         {{- toYaml .Values.podSecurityContext | nindent 8 }}
+      initContainers:
+      - name: wait-for-hasura
+        image: curlimages/curl:latest
+        env:
+        - name: HASURA_HOST
+          value: {{ .Values.services.hasura.hostname }}
+        - name: HASURA_PORT
+          value: {{ .Values.services.hasura.port | quote }}
+        - name: TIMEOUT
+          value: "60"
+        command:
+          - /bin/sh
+          - -c
+          - |
+            echo "waiting $TIMEOUT for $HASURA_PORT to be ready on host $HASURA_HOST"
+            for i in `seq 1 $TIMEOUT`;
+            do
+                echo "waiting for graphql engine"
+                version=$(curl -s http://$HASURA_HOST:$HASURA_PORT/v1/version | grep "version")
+                echo "VERSION = $version"
+                [ "$version" == "" ] && sleep 1 || exit 0
+            done
+            echo "failed waiting for $HASURA_PORT on host $HASURA_HOST" && exit 1
       containers:
         - name: {{ .Chart.Name }}
           securityContext:
@@ -33,7 +56,7 @@ spec:
           - name: ASSETS_API
             value: http://{{ .Values.services.assets.name }}:{{ .Values.services.assets.port }}
           - name: GRAPHQL_API
-            value: http://{{ .Values.services.hasura.hostname }}:{{ .Values.services.hasura.port }}/v1/graphql/
+            value: http://localhost:{{ .Values.ui.containerPort }}/graphql/
           volumeMounts:
           - mountPath: /etc/nginx/nginx.conf
             subPath: ui
